# Generated by Django 5.2.8 on 2025-11-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0003_hangout_auto_end_date_hangout_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='category',
            field=models.CharField(choices=[('drinks', 'Drinks & Bar'), ('food', 'Food & Dining'), ('sports', 'Sports & Fitness'), ('arts', 'Arts & Culture'), ('music', 'Music & Concerts'), ('outdoor', 'Outdoor Activities'), ('gaming', 'Gaming'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
