# Generated by Django on 2025-12-25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hangouts', '0005_hangout_latitude_hangout_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='kicked_users',
            field=models.ManyToManyField(blank=True, related_name='kicked_from_hangouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
