# Generated by Django 5.2.8 on 2025-11-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('hangouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='hangout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hangouts.hangout'),
        ),
    ]
