from django.urls import path
from .views import (
    UserRegistrationView,
    UserLoginView,
    UserLogoutView,
    UserProfileView,
    ProfileUpdateView,
    ProfilePhotoUploadView,
    ProfilePhotoDeleteView,
    ProfilePhotoUpdateView,
    ProfilePhotoReorderView,
    AgeVerificationUploadView,
    AgeVerificationStatusView,
    AgeVerificationApproveView,
    AgeVerificationRejectView,
    ReportCreateView,
    ReportListView,
    ReportDetailView,
    ReportUpdateStatusView,
    MyReportsView,
    PublicProfileView,
    SendConnectionRequestView,
    AcceptConnectionView,
    RejectConnectionView,
    ListFriendsView,
    PendingRequestsView,
    RemoveConnectionView,
    SearchUsersView,
    ConnectionStatusView
)
from .test_views import test_api

urlpatterns = [
    path('test/', test_api, name='api-test'),
    path('register/', UserRegistrationView.as_view(), name='user-register'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', UserLogoutView.as_view(), name='user-logout'),
    path('profile/', ProfileUpdateView.as_view(), name='user-profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/<int:user_id>/', PublicProfileView.as_view(), name='public-profile'),
    path('profile/photos/', ProfilePhotoUploadView.as_view(), name='profile-photo-upload'),
    path('profile/photos/<int:photo_id>/', ProfilePhotoDeleteView.as_view(), name='profile-photo-delete'),
    path('profile/photos/<int:photo_id>/update/', ProfilePhotoUpdateView.as_view(), name='profile-photo-update'),
    path('profile/photos/reorder/', ProfilePhotoReorderView.as_view(), name='profile-photo-reorder'),
    # Age Verification
    path('age-verification/upload/', AgeVerificationUploadView.as_view(), name='age-verification-upload'),
    path('age-verification/status/', AgeVerificationStatusView.as_view(), name='age-verification-status'),
    path('age-verification/<int:verification_id>/approve/', AgeVerificationApproveView.as_view(), name='age-verification-approve'),
    path('age-verification/<int:verification_id>/reject/', AgeVerificationRejectView.as_view(), name='age-verification-reject'),
    # Reports
    path('reports/', ReportCreateView.as_view(), name='report-create'),
    path('reports/my/', MyReportsView.as_view(), name='my-reports'),
    path('reports/all/', ReportListView.as_view(), name='report-list'),
    path('reports/<int:report_id>/', ReportDetailView.as_view(), name='report-detail'),
    path('reports/<int:report_id>/status/', ReportUpdateStatusView.as_view(), name='report-update-status'),
    # Connections/Friends
    path('connections/send/<int:user_id>/', SendConnectionRequestView.as_view(), name='send-connection'),
    path('connections/<int:connection_id>/accept/', AcceptConnectionView.as_view(), name='accept-connection'),
    path('connections/<int:connection_id>/reject/', RejectConnectionView.as_view(), name='reject-connection'),
    path('connections/<int:connection_id>/remove/', RemoveConnectionView.as_view(), name='remove-connection'),
    path('connections/friends/', ListFriendsView.as_view(), name='list-friends'),
    path('connections/pending/', PendingRequestsView.as_view(), name='pending-requests'),
    path('connections/status/<int:user_id>/', ConnectionStatusView.as_view(), name='connection-status'),
    path('search/', SearchUsersView.as_view(), name='search-users'),
]
